rabbitmq:
  auth:
    username: guest
    password: guest
    erlangCookie: mecanica-erlang-cookie

  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

  service:
    type: ClusterIP
    ports:
      amqp: 5672
      manager: 15672

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10

  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20

  plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"

  extraConfiguration: |-
    default_vhost = /
    default_user = guest
    default_pass = guest
